# POST http://localhost:3000/api/resetseqid

# POST http://localhost:3000/api/dropusers

# POST http://localhost:3000/register
# Content-Type: application/json

# {
#     "username": "gelek",
#     "email": "gelek@students.undip.ac.id",
#     "password": "ok",
#     "role": "operator"
# }

# GET http://localhost:3000/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlbGVrIiwiaWF0IjoxNjk5MTczMTM4LCJleHAiOjE2OTkxNzMxNjh9.1-bpz8RMAf3Fh8BokPGo-4t9IDzGrd8FlJf85Yuq1gY

# POST http://localhost:3000/token
# Content-Type: application/json

# {
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJnZWxlayIsImVtYWlsIjoiZ2VsZWtAc3R1ZGVudHMudW5kaXAuYWMuaWQiLCJwYXNzd29yZCI6IiQyYiQxMCQxRGFpZExPNHgxcW1Tcmthd08zRGRPRjYvenRtVDRkMTJ5RG14bnJuRDhEcHQvVUg1dm9HdSIsInJvbGUiOiJvcGVyYXRvciIsImlhdCI6MTY5OTE3MzAyOH0.1beYduV0a57kQ3XUUbt6w1BRt7FWv9U0ORsGTTU-8VE"
# }

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "gelek",
    "password": "ok"
}

# DELETE http://localhost:3000/logout
# Content-Type: application/json

# {
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJnZWxlayIsImVtYWlsIjoiZ2VsZWtAc3R1ZGVudHMudW5kaXAuYWMuaWQiLCJwYXNzd29yZCI6IiQyYiQxMCQxRGFpZExPNHgxcW1Tcmthd08zRGRPRjYvenRtVDRkMTJ5RG14bnJuRDhEcHQvVUg1dm9HdSIsInJvbGUiOiJvcGVyYXRvciIsImlhdCI6MTY5OTE3MzAyOH0.1beYduV0a57kQ3XUUbt6w1BRt7FWv9U0ORsGTTU-8VE"
# }